[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flexrml"
version = "2.2.0"
description = "FlexRML"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
dependencies = []

[project.optional-dependencies]
test = [
    "rdflib>=7,<8",
]
